### PR TITLE
Temporarily suppress 8.1 warnings to maintain backward compatibility.

### PR DESCRIPTION
**Pull request by pgraham3**
https://github.com/wildbit/postmark-php/issues/88

### CODE REVIEW

**Comment by p4veI** [comment]
Wondering, wouldn't it be better, to add the native types accordingly instead of suppressing them?

**Comment by p4veI** [comment]
Running this branch with my project still generates warnings on the `valid` method in `CaseInsensitiveArray` class, could you please add the attribute/type hint there as well?

**Comment by mfn** [comment]
> Wondering, wouldn't it be better, to add the native types accordingly instead of suppressing them?

Suppression is preferred for _upgrading_ because it will not break existing application at all (they don't know the new attributes).

Once the PHP version of this project does **not** support older PHP versions anymore _or_ a deliberate major version with (this) breaking changes is released, then it makes sense to use types.

> Running this branch with my project still generates warnings on the valid method in CaseInsensitiveArray class

I guess it was just missed and should be added, then old/new PHP versions will have no issues and everyone is happy.

**Review by tomazy — APPROVED** [review]
@pgraham3 I see that adding this attributes is a common practice in the industry so lgtm.

**Review by mfn — APPROVED** [review]
💪🏼

**Pull request merged**
